### ISSUE TITLE
We need to look at this issue in our next session.

### ISSUE THREAD

**Issue by matthewscharles** [blurringtheboundaries/learning#1]
This is just a test for our BtB session with Jay.

**Comment by blurringtheboundaries** [comment]
@Studio-Jay-Recording  Here is the link to the website version. 
https://blurringtheboundaries.github.io/learning/GitHub-ScreenReader-Instructions.html

**Comment by blurringtheboundaries** [comment]
Here's the link I mentioned to check out, then we can close this issue.

https://blurringtheboundaries.github.io/learning/javascript.html

**Comment by Studio-Jay-Recording** [comment]
This is very cool.

**Comment by blurringtheboundaries** [comment]
I think I fixed it, does it work? https://blurringtheboundaries.github.io/learning/javascript.html

**Comment by Studio-Jay-Recording** [comment]
Thanks for fixing this so quickly.
