### ISSUE TITLE
publication of pages appears to hang with invalid coffeescript

### ISSUE THREAD

**Issue by matthewscharles** [blurringtheboundaries/learning#3]
makes sense if so but this is a potential access issue for our project without a notification

running the steps from https://francisfuzz.github.io/using-coffeescript-in-pages/ which appeared to work at first

then moved to codepen and discovered error in code. it now compiles fine on there but github pages still hung.

8d841cc638ae54500268c492ec974c3de76d42c1

**Comment by matthewscharles** [comment]
just recording process in these comments: 

currently waiting on 'your site is ready to be published' for some time, and noticed I had some missing brackets in the coffeescript. this would be a pain to troubleshoot, since our plan is to edit markdown/coffeescript files during screenreader sessions

the unpredictable delay for the page to publish is already a bit of an issue. otherwise, editing markdown and coffeescript would be great for our browser-based coding

**Comment by matthewscharles** [comment]
Maybe something here:
https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-jekyll-build-errors-for-github-pages-sites

**Comment by matthewscharles** [comment]
as suspected it publishes now that I have removed the two coffeescript files 
4537d97082c17a975c7738cd1185b5a838eca877

going to try re-introducing them one at a time.

**Comment by matthewscharles** [comment]
Yup that works
1aff013

It seems to get stuck when I add the non-coffeescript tone material
[ff70242](https://github.com/blurringtheboundaries/learning/commit/ff702428ad9f6029eb1b1be030912b702f642d75)
problem is I'm not fluent enough yet!

**Comment by blurringtheboundaries** [comment]
seems to be updating now. I think it's safe to say that the invalid coffeescript was causing the publication to hang, and while this is going to be a barrier in the future, I'll close this to come back to later if we need to.
